#ifndef _PANUTI_SYSCALL_NO_H
#define _PANUTI_SYSCALL_NO_H

#define SYSHANDLER_WRITE 0
#define SYSHANDLER_EXIT 1
#define SYSHANDLER_OPEN 2
#define SYSHANDLER_READ 3
#define SYSHANDLER_ACTIVATE 4
#define SYSHANDLER_WAIT 5
#define SYSHANDLER_CLOSE 6
#define SYSHANDLER_MKDIR 7
#define SYSHANDLER_REGFIND 8
#define SYSHANDLER_REGROOT 9

#endif