#ifndef _PANUTI_SYSCALL_NO_H
#define _PANUTI_SYSCALL_NO_H

#define SYSHANDLER_WRITE 0
#define SYSHANDLER_EXIT 1
#define SYSHANDLER_OPEN 2
#define SYSHANDLER_WAIT 3
#define SYSHANDLER_ACTIVATE 4
#define SYSHANDLER_CLOSE 5
#define SYSHANDLER_POINT_CREATE 6

#endif