#ifndef _PANUTI_ERRNO_H
#define _PANUTI_ERRNO_H

#define PANUTIERRORCODE(code) ((code) + 0x80000000)

// error codes first
#define PANUTIERRNO_PLAINERR PANUTIERRORCODE(0)
#define PANUTIERRNO_INVALIDSYSCALL PANUTIERRORCODE(1)
#define PANUTIERRNO_UNSUPPORTEDOP PANUTIERRORCODE(2)
#define PANUTIERRNO_NOTFOUND PANUTIERRORCODE(3)
#define PANUTIERRNO_NOFDS PANUTIERRORCODE(4)
#define PANUTIERRNO_BADFD PANUTIERRORCODE(5)

// success codes
#define PANUTIERRNO_PLAINSUCCESS 0

#endif