#ifndef _PANUTI_KEYBOARD_H
#define _PANUTI_KEYBOARD_H

#include <stdbool.h>

typedef enum keycode {
	KEYCODE_NONE,
	KEYCODE_A,
	KEYCODE_B,
	KEYCODE_C,
	KEYCODE_D,
	KEYCODE_E,
	KEYCODE_F,
	KEYCODE_G,
	KEYCODE_H,
	KEYCODE_I,
	KEYCODE_J,
	KEYCODE_K,
	KEYCODE_L,
	KEYCODE_M,
	KEYCODE_N,
	KEYCODE_O,
	KEYCODE_P,
	KEYCODE_Q,
	KEYCODE_R,
	KEYCODE_S,
	KEYCODE_T,
	KEYCODE_U,
	KEYCODE_V,
	KEYCODE_W,
	KEYCODE_X,
	KEYCODE_Y,
	KEYCODE_Z,
	KEYCODE_0,
	KEYCODE_1,
	KEYCODE_2,
	KEYCODE_3,
	KEYCODE_4,
	KEYCODE_5,
	KEYCODE_6,
	KEYCODE_7,
	KEYCODE_8,
	KEYCODE_9,
	KEYCODE_PERIOD,
	KEYCODE_COMMA,
	KEYCODE_SEMICOLON,
	KEYCODE_COLON,
	KEYCODE_APOSTROPHE,
	KEYCODE_QUOTE,
	KEYCODE_EXCLAMATION,
	KEYCODE_QUESTION,
	KEYCODE_MINUS,
	KEYCODE_UNDERSCORE,
	KEYCODE_EQUALS,
	KEYCODE_PLUS,
	KEYCODE_SLASH,
	KEYCODE_BACKSLASH,
	KEYCODE_LPAREN,
	KEYCODE_RPAREN,
	KEYCODE_LBRACKET,
	KEYCODE_RBRACKET,
	KEYCODE_LBRACE,
	KEYCODE_RBRACE,
	KEYCODE_LESS,
	KEYCODE_GREATER,
	KEYCODE_AT,
	KEYCODE_HASH,
	KEYCODE_DOLLAR,
	KEYCODE_PERCENT,
	KEYCODE_CARET,
	KEYCODE_AMPERSAND,
	KEYCODE_STAR,
	KEYCODE_TILDE,
	KEYCODE_LSHIFT,
	KEYCODE_RSHIFT,
	KEYCODE_LALT,
	KEYCODE_RALT,
	KEYCODE_LCTRL,
	KEYCODE_RCTRL,
	KEYCODE_CAPS_LOCK,
	KEYCODE_SCROLL_LOCK,
	KEYCODE_NUM_LOCK,
	KEYCODE_SPACE,
	KEYCODE_TAB,
	KEYCODE_BACKSPACE,
	KEYCODE_ENTER
} keycode_t;

typedef struct keypacket {
	keycode_t keycode;
	
	bool pressed;
	
	bool shift;
	bool ctrl;
	bool alt;

	bool caps_lock;
	bool scroll_lock;
	bool num_lock;
} keypacket_t;

#endif